authors:
  dlicudi:
    name: Duane Licudi
    description: cockpitdecks-configs contributor
    avatar: https://avatars.githubusercontent.com/u/2129148?v=4
    slug: dlicudi
    url: https://dlicudi.github.io/cockpitdecks-configs
