# This is at layout level
default-icon-color: (94, 111, 130)
default-text-bg-color: (40, 40, 40)
default-label-color: blue
default-label-font: DIN Bold.ttf
default-label-size: 13
default-text-size: 24
default-label-position: ct
default-homepage-name: pfi
default-vibrate: BUZZ