site_name: Cockpitdecks Configs

theme:
  name: material
 
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags
  - search
repo_url: https://github.com/dlicudi/cockpitdecks-configs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
